In [ ]:
Central Park Weather Station - 72505394728

In [2]:
import logging
import os
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [39]:
weather = pd.read_csv('NYC.csv')
c2023 = pd.read_csv('202308-citibike-tripdata_5.csv',dtype={'ride_id':'string','rideable_type':'string','started_at':'string'
                                              ,'ended_at':'string','start_station_name':'string','start_station_id':'string'
                                              ,'end_station_name':'string','end_station_id':'string',
                                              'start_lat':'float64','start_lng':'float64','end_lat':'float64','end_lng':'float64',
                                              'member_casual':'string'})
#c2023['started_at']=c2023['started_at'].apply(pd.to_datetime,format='%Y-%m-%d %H:%M:%S')
c2023['datehour']=c2023['started_at'].str.split(' ',expand=True)[0]+'-'+c2023['started_at'].str.split(' ',expand=True)[1].str.split(':',expand=True)[0]
#c2023.groupby('datehour')
weather['date']=weather['valid'].str.split(' ',expand=True)[0]
weather['hour']=weather['valid'].str.split(' ',expand=True)[1].str.split(':',expand=True)[0]
weather[['date','hour','tmpf','p01i']]

             date hour  tmpf  p01i
0      2022-01-01   00  51.0   0.0
1      2022-01-01   01  51.0   0.0
2      2022-01-01   02  52.0   0.0
3      2022-01-01   03  51.0   0.0
4      2022-01-01   04  51.0   0.0
...           ...  ...   ...   ...
17389  2023-12-30   18  45.0   0.0
17390  2023-12-30   20  46.0   0.0
17391  2023-12-30   21  45.0   0.0
17392  2023-12-30   22  45.0   0.0
17393  2023-12-30   23  44.0   0.0

[17394 rows x 4 columns]